services:
  - type: web
    name: agenda-web
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: agenda-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: agenda-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: agenda-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: agenda-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: agenda-db
          property: password

  - type: static
    name: agenda-frontend
    rootDir: ./frontend
    buildCommand: npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://agenda-web-8gfo.onrender.com/api

databases:
  - name: agenda-db
    databaseName: agenda_db
    user: agendauser
    plan: free